from enum import Enum


class MonitoringStatus(Enum):
    PLANNED = "PLANNED"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    STOPPED = "STOPPED"
    COMPLETED = "COMPLETED"

class MonitoringCategory(Enum):
    FLOOD = "FLOOD"
    CYCLONE = "CYCLONE"
    WILDFIRE = "WILDFIRE"
    EARTHQUAKE = "EARTHQUAKE"
    LANDSLIDE = "LANDSLIDE"
    HEATWAVE = "HEATWAVE"
    CYBERSECURITY = "CYBERSECURITY"
    INFRASTRUCTURE_FAILURE = "INFRASTRUCTURE_FAILURE"
    PUBLIC_HEALTH = "PUBLIC_HEALTH"
    CUSTOM = "CUSTOM"

class TargetType(Enum):
    REGION = "REGION"
    CITY = "CITY"
    DISTRICT = "DISTRICT"
    COUNTRY = "COUNTRY"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    ORGANIZATION = "ORGANIZATION"
    FACILITY = "FACILITY"
    TOPIC = "TOPIC"
    CUSTOM = "CUSTOM"

class MonitoringFrequency(Enum):
    REALTIME = "REALTIME"
    FIVE_MINUTES = "FIVE_MINUTES"
    HOURLY = "HOURLY"
    DAILY = "DAILY"
    CUSTOM = "CUSTOM"

class SituationState(Enum):
    NORMAL = "NORMAL"
    WATCH = "WATCH"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
