from datetime import datetime
from typing import Any, Dict, Optional

from pydantic import BaseModel, ConfigDict, Field

from features.evidence.domain import EvidenceType


class EvidenceBase(BaseModel):
    title: str = Field(..., description="Title of the evidence")
    description: Optional[str] = Field(None, description="Detailed description")
    source: Optional[str] = Field(None, description="Source of the evidence (e.g. system, user, tool)")
    evidence_type: EvidenceType = Field(..., description="Type of evidence data")
    content: Optional[str] = Field(None, description="The core evidence content (e.g. text or URL)")
    confidence_score: Optional[float] = Field(None, ge=0.0, le=1.0, description="Confidence score if generated by AI")
    collected_at: Optional[datetime] = Field(None, description="When the evidence was actually collected")
    evidence_metadata: Optional[Dict[str, Any]] = Field(None, description="Additional structured metadata")

class EvidenceCreate(EvidenceBase):
    operation_id: Optional[str] = None
    incident_id: Optional[str] = None
    mission_id: Optional[str] = None
    workflow_id: Optional[str] = None

class EvidenceUpdate(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    content: Optional[str] = None
    confidence_score: Optional[float] = None
    evidence_metadata: Optional[Dict[str, Any]] = None

class EvidenceRead(EvidenceBase):
    id: str
    submitted_by: Optional[str]
    operation_id: Optional[str]
    incident_id: Optional[str]
    mission_id: Optional[str]
    workflow_id: Optional[str]
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)
