from enum import Enum

class OperationStatus(str, Enum):
    PLANNED = "PLANNED"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"

class OperationCategory(str, Enum):
    WEATHER = "WEATHER"
    CYBERSECURITY = "CYBERSECURITY"
    PUBLIC_HEALTH = "PUBLIC_HEALTH"
    NATURAL_DISASTER = "NATURAL_DISASTER"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    TRANSPORTATION = "TRANSPORTATION"
    INDUSTRIAL = "INDUSTRIAL"
    HUMANITARIAN = "HUMANITARIAN"
    ENVIRONMENTAL = "ENVIRONMENTAL"
    GENERIC = "GENERIC"

class OperationPriority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
